[package]
name = "dbus-watch"
version = "0.1.0"
authors = ["Mike Panetta <panetta.mike@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dbus="0.8.1"
newt = "0.6.2"
